import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, apiMessage } from '../../api/client.js';
import { formatDate, formatMoney } from '../utils/format.js';
import { EmptyState, LinkButton, LoadingBlock, Notice, PageHeader, StatusBadge } from '../components/UI.jsx';

export default function ClientDetailPage() {
  const { publicId } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.get(`/clients/${publicId}`).then(({ data: value }) => setData(value)).catch((requestError) => setError(apiMessage(requestError))); }, [publicId]);
  return <>{!data ? <><PageHeader eyebrow="Client record" title="Client" /><Notice>{error}</Notice><LoadingBlock /></> : <><PageHeader eyebrow="Client record" title={data.client.name} description={data.client.company || 'Individual client'} actions={<><LinkButton to={`/finance/clients/${publicId}/edit`} variant="secondary">Edit details</LinkButton><LinkButton to={`/finance/invoices/new?client=${publicId}`}>+ New invoice</LinkButton></>} /><div className="client-detail-grid"><aside className="panel client-profile"><div className="client-avatar large">{data.client.name.slice(0, 2).toUpperCase()}</div><h2>{data.client.name}</h2><p>{data.client.email || 'No email'}</p><p>{data.client.phone || 'No phone'}</p><address>{data.client.address || 'No address added'}</address>{data.client.notes && <div className="profile-note"><span>NOTES</span>{data.client.notes}</div>}</aside><section>{data.metrics.map((metric) => <div className="metric-grid client-metrics" key={metric.currency}><article><span>Total invoiced · {metric.currency}</span><strong>{formatMoney(metric.invoiced, metric.currency)}</strong></article><article><span>Total paid · {metric.currency}</span><strong>{formatMoney(metric.paid, metric.currency)}</strong></article><article><span>Outstanding · {metric.currency}</span><strong>{formatMoney(metric.outstanding, metric.currency)}</strong></article></div>)}<div className="panel"><div className="panel-head"><h2>Invoice history</h2></div>{data.invoices.length ? <div className="responsive-table"><table><thead><tr><th>Invoice</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.invoices.map((invoice) => <tr key={invoice.publicId}><td><Link to={`/finance/invoices/${invoice.publicId}`}>{invoice.number}</Link></td><td>{formatDate(invoice.issueDate)}</td><td>{formatMoney(invoice.total, invoice.currency)}</td><td><StatusBadge status={invoice.displayStatus} /></td></tr>)}</tbody></table></div> : <EmptyState title="No invoice history" body="Create an invoice for this client to begin." action="Create invoice" to={`/finance/invoices/new?client=${publicId}`} />}</div></section></div></>}</>;
}
